invoiceplane:
  build: .
  ports :
   - "10180:80"
  volumes:
   - /srv/docker/invoicePlane/uploads:/var/www/html/uploads
  links:
   - database:database
phpmyadmin:
   image: corbinu/docker-phpmyadmin
   ports :
    - "10181:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=password
   links:
    - database:mysql
database:
  image: mysql:5.5
  volumes:
   - /srv/docker/invoicePlane/mysql:/var/lib/mysql/
  environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=invoicePlane
     - MYSQL_USER=invoicePlane
     - MYSQL_PASSWORD=password
