invoiceplane:
  build: 1twitif/invoiceplane
#  build: docker-invoiceplane
  ports :
   - "10180:80"
  volumes:
#   - /srv/docker/invoicePlane/files:/var/www/html/
  links:
   - database
phpmyadmin:
   image: corbinu/docker-phpmyadmin
   ports :
    - "10181:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=password
   links:
    - database:mysql
database:
  image: mysql:5.5
#  ports:
#   - "3306:3306"  
  volumes:
#   - /srv/docker/invoicePlane/mysql:/var/lib/mysql/
  environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=mysite
     - MYSQL_USER=invoicePlane
     - MYSQL_PASSWORD=password